drop table if exists book cascade;
drop table if exists author;
drop table if exists genre;
drop table if exists comment;

create table book(id BIGINT NOT NULL primary key generated by default as identity, title varchar(255), author_id bigint, genre_id bigint);
create table genre(id bigint NOT NULL primary key generated by default as identity, title varchar(255));
create table author(id bigint NOT NULL primary key generated by default as identity, first_name varchar(255), last_name varchar(255));
create table comment(id bigint NOT NULL primary key generated by default as identity, comment varchar(255), book_id bigint references book (id) on delete cascade);

alter table book
add constraint fk_bookGenre
foreign key (genre_id) references genre(Id);

alter table book
add constraint fk_bookAuthor
foreign key (author_id) references author(Id);