Spring:
  datasource:
    platform: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    schema: schema.sql
    data: data.sql
    initialization-mode: always
    username: sa
    password: