spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    platform: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    password:

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /datarest

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,logfile,histrix.stream

  endpoint:
    health:
      show-details: always

  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
logging:
  file:
    name: logfile.txt
hystrix.command.findReservedBooks.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.command.findReservedBookById.execution.isolation.thread.timeoutInMilliseconds: 5000