spring:
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.netrax.mongock.changelog